### ISSUE TITLE
Confusing Documentation...  

### ISSUE THREAD

**Issue by ajoslin103** [mobxjs/mobx-react-docz#113]
Personally, I find documenting a difficult thing.  

By the time I write the docs my mind is deep in the code and I write with clarity.  Since I can never go back to the code with a beginners mind, I never realize that while I was being very nuanced and direct, my words would only make sense to initiates - that novices would not benefit from them at first.

I was slow to realize this, and I still don't know what to do about it.  

Somewhat recently I read a really amazing book: Emotional Design.  It didn't help me at all to become more emotional [IDK about that stuff] but it really helped me to begin to understand why I seemed to be the only one that understood things I built.  Or at least it seemed to at the time.  Whatever.

Anyway, 

I come to these docs and the Introduction example doesn't seem very React-like, but I read it until I just have to click onwards 

And I get to Libraries, and in a note describing something that happened in 2018, it obsoletes all the code I was just trying to read and understand.  And I get annoyed and frustrated because apparently I was puzzling out `mobx-react` when I should be breezing along with `mobx-react-lite`.

Our world moves very fast, and whole swaths of a library can be deprecated overnight - perhaps you could prefix the docs with a change-log/road-map list of pointers to which docs are for what users?

Looking for this?  Start Here!  

Write your code that way?  Start There!

Diving back in.

Cheers!

**Comment by FredyC** [comment]
Stay tuned, this site will be gone as soon as MobX 6 is fresh out of the oven with docs overhaul. Everything will be consolidated in one place. You can, of course, help to review the current state of it and point out confusions.

https://deploy-preview-2327--mobx-docs.netlify.app/
https://github.com/mobxjs/mobx/pull/2327

**Comment by ajoslin103** [comment]
how do I (can I?) install the mobx v6 in-progress?

**Comment by FredyC** [comment]
Install `mobx@beta`, should work with the latest `mobx-react-lite`.

**Comment by ajoslin103** [comment]
I do apologize for bothering you, I can't seem to find the answer to this on the internet....

I'm using function-style components and Typescript with React

```
import React from 'react';
import PropTypes, { InferProps } from 'prop-types';
function GameField({ gameProps }: InferProps<typeof GameField.propTypes>) {
 [whatever...]
};
GameField.propTypes = {
  gameProps: PropTypes.instanceOf(GameProps).isRequired,
};
export default GameField;
```

I had to use inferProps  to avoid the error:

    Binding element 'gameProps' implicitly has an 'any' type.  TS7031

Now I can't figure out how to wrap them in an observer without getting that same error 

    Binding element 'gameProps' implicitly has an 'any' type.  TS7031

How would you wrap this usage?

Thanks

**Comment by FredyC** [comment]
Try StackOverflow, I am not your personal adviser, sorry ;)
