### ISSUE TITLE
Clearer migration guide and context usage

### ISSUE THREAD

**Issue by bluepeter** [mobxjs/mobx-react-docz#33]
I have been working with the migration guide (with non-Typescript Javascript) and it is not clear to me. Particularly this page https://mobx-react.js.org/recipes-context

In the context setup we have this code:

```
import React from 'react'
import { createStore, TStore } from './createStore'
import { useLocalStore } from 'mobx-react-lite'

const storeContext = React.createContext<TStore | null>(null)

export const StoreProvider = ({ children }) => {
  const store = useLocalStore(createStore)
  return <storeContext.Provider value={store}>{children}</storeContext.Provider>
}

export const useStore = () => {
  const store = React.useContext(storeContext)
  if (!store) {
    // this is especially useful in TypeScript so you don't need to be checking for null all the time
    throw new Error('You have forgot to use StoreProvider, shame on you.')
  }
  return store
}
```

At minimum, I'd recommend adding the filename for each code snippet as it is not immediately clear.

But in this case, it appears there are two `export`s for `useStore` and `StoreProvider`, but the examples don't give clear examples of usage.

In my case, I am attempting to `useStore` with `const storeContext = createContext(useLocalStore(myStore()));` and I get an error `Hooks can only be called inside of the body of a function component`.

I'm fairly handy with Javascript, but this guide really isn't clear and could be better structured and with clearer examples. I'd love some clarity of this specific situation.

**Comment by FredyC** [comment]
Thanks for the feedback, although I am not sure what to make more clear. Each snippet is a single file, not sure if it matters how you name it. You can see `useStore` in two subsequent examples, what's not clear about that?

The `StoreProvider` is basically optional (it's mentioned in blue box), but you certainly cannot use `useLocalStore` there. However you can do just `const storeContext = createContext(myStore())`. How you setup the `myStore` is up to you. It can be `mobx-state-tree` or class-based store, but not the `useLocalStore`.

If you have some ideas about how to improve that recipe, feel free to submit a PR.

**Comment by bluepeter** [comment]
Thanks, I will try to get it working now thanks to your suggestions.

At minimum, I would recommend adding the filename of each example file beforehand. This is similar to official React approach:

![screenshot-reactjs org-2019 08 25-11-01-52](https://user-images.githubusercontent.com/2158187/63653902-dd2ee200-c727-11e9-97c4-863d86fc1822.png)

**Comment by bluepeter** [comment]
@FredyC I am having trouble using `this.` when NOT using `useLocalStore` and the comment `note the use of this which refers to observable instance of the store` (in https://mobx-react.js.org/recipes-context). 

I have a simple store like the following:

```
const myStore = () => {
  return {
    test: () => {
      console.log("Test");
    },
    checkIfReady: () => {
      this.test();
    },
  };
};

const storeContext = createContext(myStore());

export const ThumbnailStore = () => {
  const store = useContext(storeContext);
  return store;
};
```

But when I get error: `TypeError: Cannot read property 'test' of undefined` in reference to `this.test()`... if I am not using `useLocalStore()` and wrapping component, I guess I cannot use `this` to self-reference?

**Comment by FredyC** [comment]
Well, that's common trap with ES6. You cannot use anonymous function, a.k.a arrow function which simply "steals" `this` and doesn't care about any sort of binding. You have to do `test() { ... }`

**Comment by bluepeter** [comment]
D'oh!

**Comment by bluepeter** [comment]
@FredyC can I not easily mix MobX with `useContext` during migration? The following code snippet:

<img width="2010" alt="Screen Shot 2019-08-25 at 3 57 40 PM" src="https://user-images.githubusercontent.com/2158187/63657057-4545ee00-c751-11e9-9fe4-4abd003afdfe.png">

In this, I get `undefined` when I attempt `const context = useContext(ThumbnailContext); console.log(context)`

**Comment by bluepeter** [comment]
It looks like I will need to use `MobXProviderContext` while migrating? Is there a clear, complete example on how to use this? :(
