### ISSUE TITLE
How to use stores outside of components for "Multiple global stores" example?

### ISSUE THREAD

**Issue by sergeysibara** [mobxjs/mobx-react-docz#91]
About https://mobx-react.js.org/recipes-context#multiple-global-stores
I want to use stores in components and outside of components (in business logic layer). 
I don`t see way to implement it using only react context, without using import store to another file(s).

**Comment by FredyC** [comment]
Perhaps @tjhillard can help you out here as the author of that documentation section. I don't use that pattern.

**Comment by tjhillard** [comment]
@sergeysibara Maybe this [CodeSandbox demo](https://codesandbox.io/s/react-mobx-global-state-management-lxcp6?file=/src/index.tsx) can help point you in the right direction. Cheers.

**Comment by sergeysibara** [comment]
Thank you for reply!
I see that this is impossible without storing the store in a global variable.

**Comment by sergeysibara** [comment]
I using approach with using global stores in middleware (a layer between api and store). 
For example:
https://github.com/sergeysibara/mobx-react-4-tier-architecture
https://github.com/sergeysibara/mobx-react-4-tier-architecture/blob/master/src/modules/actions/BaseActions.ts

React context is not suitable for it.
I close the task.
